### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by cosine123** [huiwy/reflection-on-trees#2]
(rot) wangks@3dimage-31:/data/wangks/reflection-on-trees/reflection-on-trees$ sh blocksworld_rot.sh prompts/bw/pool_prompt_rot.json
Traceback (most recent call last):
  File "/data/wangks/reflection-on-trees/reflection-on-trees/examples/blocksworld/rap.py", line 60, in <module>
    fire.Fire(rap_bw) # user will need to switch the model in the code
  File "/data/wangks/anaconda3/envs/rot/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/wangks/anaconda3/envs/rot/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data/wangks/anaconda3/envs/rot/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/wangks/reflection-on-trees/reflection-on-trees/examples/blocksworld/rap.py", line 51, in rap_bw
    search_algo = MCTS(**search_algo_params)
TypeError: MCTS.__init__() got an unexpected keyword argument 'n_actions'
Traceback (most recent call last):
  File "/data/wangks/reflection-on-trees/reflection-on-trees/blocksworld_control.py", line 60, in <module>
    with open(f'{log_path}/time_consumed.txt', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/bw/step_4/phi-2_default_mcts_10_20240509-0001/time_consumed.txt'
Traceback (most recent call last):
  File "/data/wangks/reflection-on-trees/reflection-on-trees/rot_scripts/blocksworld_analysis.py", line 56, in <module>
    aa = analyze.Analysis.from_file(f"{path}/{i+1}.pkl", Evaluator(d, args.steps, config_file, domain_file))
  File "/data/wangks/reflection-on-trees/reflection-on-trees/reasoners/visualization/analyze.py", line 36, in from_file
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/bw/step_4/phi-2_default_mcts_10_20240509-0001/algo_output/1.pkl'
Traceback (most recent call last):
  File "/data/wangks/reflection-on-trees/reflection-on-trees/rot_scripts/blocksworld_generate_rot_prompt.py", line 12, in <module>
    rot = json.load(open(f'{args.path}'))
FileNotFoundError: [Errno 2] No such file or directory: 'logs/bw/step_4/phi-2_default_mcts_10_20240509-0001/rot_analysis.json'

**Comment by huiwy** [comment]
fixed
